README.md, src/__tests__/test-process-tpl.js, src/process-tpl.js
=> fix mistakenly import scripts and styles in comment

src/__tests__/test-process-tpl.js, src/index.js, src/process-tpl.js
=> feat: add support parsing inline styles and scripts

example/index.html, example/template.html, package.json, src/__tests__/test-process-tpl.js, src/process-tpl.js
添加 ignore 属性
微前端场景：子项目为了独立运行，引入主项目的公共依赖。当主项目和子项目合并运行时，忽略子项目中公共依赖
=> feat: add ignore attribute

src/__tests__/test-process-tpl.js, src/process-tpl.js
https://github.com/umijs/qiankun/issues/64#issuecomment-530199818
close https://github.com/kuitos/import-html-entry/issues/8
=> :bug:  regex not match resource with no quotation marks

index.d.ts, package.json, src/__tests__/test-custome-fetch.js, src/index.js
待讨论：
1. 是否有必要改写为 class （从 fetch 这个例子来看，层层传递似乎显得不够优雅，改写为 class 则只需要调实例上的方法）
2. custom fetch UT 的姿势
cc @kuitos 
close https://github.com/kuitos/import-html-entry/issues/7
=> :sparkles: support custom fetch

src/index.js
https://github.com/umijs/qiankun/issues/137#issuecomment-553223033
=> fix: assetPublicPath bug

src/index.js
scene: [qiankun](https://github.com/Veath/qiankun/blob/0f05af91b428d7e13ce9e359bf87c8a1fecc22ce/src/hijackers/dynamicScript.ts#L1)
dynamic script add sandbox window
if applicable, i will merge later into qiankun
=> export execScripts method

src/index.js
=> 将reject改为resolve

package.json
close https://github.com/umijs/qiankun/issues/185
=> :bug: fix the bug with caniuse

src/index.js
close https://github.com/umijs/qiankun/issues/254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuitos/import-html-entry/24)
=> :bug: disable performance if not support

src/index.js
close https://github.com/kuitos/import-html-entry/pull/23
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuitos/import-html-entry/25)
=> :loud_sound: add warning if get domain false

package.json, src/__tests__/test-process-tpl.js, src/__tests__/test-utils.js, src/index.js, src/process-tpl.js, src/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuitos/import-html-entry/26)
=> :sparkles: 支持解析 html 中相对路径的资源

src/index.js
ref https://github.com/umijs/qiankun/issues/274
=> :sparkles: support config entry using getTemplate

.babelrc, index.d.ts, package.json, src/__tests__/test-process-tpl.js, src/index.js, src/process-tpl.js, src/utils.js
ref https://github.com/umijs/qiankun/issues/310
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuitos/import-html-entry/29)
=> :sparkles: support async script loading

src/__tests__/test-process-tpl.js, src/process-tpl.js
resolve https://github.com/umijs/qiankun/issues/309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuitos/import-html-entry/28)
=> :sparkles: disable preload and prefetch to avoid duplicating assets downloading

src/index.js, src/utils.js
1. 更新了 `getGlobalProp` 和 `noteGlobalProps` 
2.  `https://polyfill.io/` 处的 fetch 会导致 IE11 下 getGlobalProp 出错
=> feat: update getGlobalProp & noteGlobalProps

src/index.js, src/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuitos/import-html-entry/33)
=> :bug: add global to shouldSkipProperty function and conditional add with closure

src/index.js
=> fix: remove semicolon

src/index.js
resolve https://github.com/umijs/qiankun/issues/433
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuitos/import-html-entry/37)
=> :sparkles: add sourceURL mapping to inline script optimize debug experience

src/__tests__/test-config-entry.js, src/index.js
resolve https://github.com/umijs/qiankun/issues/429
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuitos/import-html-entry/39)
=> :sparkles: support config entry style auto removing

src/__tests__/test-process-tpl.js, src/process-tpl.js
除了 MIME type 是 module 跟 javascript，其他的保持原状一概不处理。
https://github.com/kuitos/import-html-entry/pull/44
resolve https://github.com/umijs/qiankun/issues/596
=> fix：特殊 type 的 script 标签不做处理，原样插入

src/__tests__/test-process-tpl.js, src/process-tpl.js
ref #45
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuitos/import-html-entry/46)
=> :bug: src attr should be ignore while type is not a valid JavaScript MMIE type

.gitignore, .travis.yml, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuitos/import-html-entry/47)
=> :construction_worker: add code coverage

src/__tests__/fixtures/ignore-js-css.html, src/__tests__/test-process-tpl.js, src/process-tpl.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuitos/import-html-entry/49)
=> :bug: fix ignore not working issue with newline

index.d.ts, src/index.js, src/utils.js
see https://github.com/umijs/qiankun/issues/791#issuecomment-663333227
=> 优化：当子项目使用 config entry 并自定义 getPublicPath 时，getPublicPath 函数能拿到更多的参数

src/index.js
resolve https://github.com/umijs/qiankun/issues/886
=> 🐛 entry script error must be thrown to settle the promise

src/index.js
close https://github.com/brickspert/umi-micro-apps/issues/1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuitos/import-html-entry/57)
=> ✨ support nested micro app scenario

src/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuitos/import-html-entry/60)
=> ⏫ sync from system.js

src/index.js
rollup 打包会加上 globalThis 判断 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuitos/import-html-entry/65)
=> 🐛 proxy globalThis

src/index.js
捕捉 aborted 异常，如 [1330](https://github.com/umijs/qiankun/pull/1330)
=> fix: catch aborted error

src/utils.js
new URL(url, base), 传了location.href作为第二个base参数，构造函数是可以使用 // 前缀的url的
=> chore: optimize URL constructor argument

index.d.ts, src/index.js, src/process-tpl.js
如 https://github.com/umijs/qiankun/pull/1756#issuecomment-931159441 里的沟通，新增postProcessTemplate配置，支持业务方在processTpl后自定义处理模板结果
=> feat: support postProcessTemplate configuration

README.md, src/index.js
Add API list：
- importHTML
- importEntry
- execScripts
=> Add document details

index.d.ts, src/index.js, src/process-tpl.js
resolve https://github.com/kuitos/import-html-entry/pull/81
inspired by https://github.com/endojs/endo/blob/b73a7b8f921818866bb2bf0b982fb93fefaa1860/packages/ses/src/make-evaluate-factory.js#L64
=> ⚡️ use scoped globals to improve sandbox performance

src/index.js, src/utils.js
ref https://github.com/kuitos/import-html-entry/pull/82
=> ✨ enable scoped globals by configuration

src/__tests__/test-process-tpl.js, src/process-tpl.js, src/utils.js
- resolves https://github.com/umijs/qiankun/issues/2378
=> 🐛fix the scene where the url contains escape characters
